'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18444
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Data
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18444.
'
Namespace RegisterReview
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="RegReviewSoap", [Namespace]:="http://localhost.org/")>  _
    Partial Public Class RegReview
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private RegisterReviewedServiceXMLOperationCompleted As System.Threading.SendOrPostCallback
        
        Private RegisterReviewedServiceOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.Kiosk.My.MySettings.Default.Kiosk_RegisterReview_RegReview
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event RegisterReviewedServiceXMLCompleted As RegisterReviewedServiceXMLCompletedEventHandler
        
        '''<remarks/>
        Public Event RegisterReviewedServiceCompleted As RegisterReviewedServiceCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://localhost.org/RegisterReviewedServiceXML", RequestNamespace:="http://localhost.org/", ResponseNamespace:="http://localhost.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function RegisterReviewedServiceXML(ByVal scanID As Integer) As String
            Dim results() As Object = Me.Invoke("RegisterReviewedServiceXML", New Object() {scanID})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub RegisterReviewedServiceXMLAsync(ByVal scanID As Integer)
            Me.RegisterReviewedServiceXMLAsync(scanID, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub RegisterReviewedServiceXMLAsync(ByVal scanID As Integer, ByVal userState As Object)
            If (Me.RegisterReviewedServiceXMLOperationCompleted Is Nothing) Then
                Me.RegisterReviewedServiceXMLOperationCompleted = AddressOf Me.OnRegisterReviewedServiceXMLOperationCompleted
            End If
            Me.InvokeAsync("RegisterReviewedServiceXML", New Object() {scanID}, Me.RegisterReviewedServiceXMLOperationCompleted, userState)
        End Sub
        
        Private Sub OnRegisterReviewedServiceXMLOperationCompleted(ByVal arg As Object)
            If (Not (Me.RegisterReviewedServiceXMLCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent RegisterReviewedServiceXMLCompleted(Me, New RegisterReviewedServiceXMLCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://localhost.org/RegisterReviewedService", RequestNamespace:="http://localhost.org/", ResponseNamespace:="http://localhost.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function RegisterReviewedService(ByVal scanID As Integer) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("RegisterReviewedService", New Object() {scanID})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Overloads Sub RegisterReviewedServiceAsync(ByVal scanID As Integer)
            Me.RegisterReviewedServiceAsync(scanID, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub RegisterReviewedServiceAsync(ByVal scanID As Integer, ByVal userState As Object)
            If (Me.RegisterReviewedServiceOperationCompleted Is Nothing) Then
                Me.RegisterReviewedServiceOperationCompleted = AddressOf Me.OnRegisterReviewedServiceOperationCompleted
            End If
            Me.InvokeAsync("RegisterReviewedService", New Object() {scanID}, Me.RegisterReviewedServiceOperationCompleted, userState)
        End Sub
        
        Private Sub OnRegisterReviewedServiceOperationCompleted(ByVal arg As Object)
            If (Not (Me.RegisterReviewedServiceCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent RegisterReviewedServiceCompleted(Me, New RegisterReviewedServiceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")>  _
    Public Delegate Sub RegisterReviewedServiceXMLCompletedEventHandler(ByVal sender As Object, ByVal e As RegisterReviewedServiceXMLCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class RegisterReviewedServiceXMLCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")>  _
    Public Delegate Sub RegisterReviewedServiceCompletedEventHandler(ByVal sender As Object, ByVal e As RegisterReviewedServiceCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class RegisterReviewedServiceCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Data.DataSet
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Data.DataSet)
            End Get
        End Property
    End Class
End Namespace
